import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.nav}>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Services </li>
            <li>Blogs</li>
          </ul>
        </nav>

          <sahith style={styles.bod}>
            <header>
              <h1>Hunting coder</h1>
              <div>A blog for hunters</div>
            </header>
          </sahith>
          
      </main>
    </>
  );
}
